services:
  - type: web
    name: sf-spots-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn sf-spots-backend.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sf_spots_db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12.0

databases:
  - name: sf_spots_db
    databaseName: sf_spots_db
    user: sf_spots_user
    plan: free
